# Generated by Django 4.0.4 on 2022-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('subject_code', models.CharField(max_length=10)),
                ('date_of_exam', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('scheduled_by', models.CharField(max_length=50)),
            ],
        ),
    ]
