# Generated by Django 4.0.4 on 2022-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('employment_number', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=25)),
            ],
        ),
    ]
