# Generated by Django 4.0.4 on 2022-06-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_t_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_profile',
            name='username',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
