# Generated by Django 4.0.4 on 2022-05-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_students',
            name='registered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
