# Generated by Django 4.0.4 on 2022-06-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_all_students_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('roll_number', models.BigIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('joined', models.DateField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
