# Generated by Django 4.0.4 on 2022-06-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_students_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_students',
            name='registered_at',
            field=models.DateTimeField(),
        ),
    ]
