# Generated by Django 4.0.4 on 2022-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_all_students_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_students',
            name='passwd',
            field=models.CharField(default='user12345', max_length=20),
        ),
    ]
