# Generated by Django 4.0.4 on 2022-06-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_passwd_all_students_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_students',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
